language: java
install: true

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8

jdk:
- oraclejdk8

script:
- ./gradlew check -S --info --console plain

after_success:
- bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master