language: csharp
language: java
install: true

env:
  global:
    - LOCAL_ENV_RUN=true

matrix:
  include:
    - os: linux
      dist: xenial
      jdk:
        - openjdk8
      mono:
        - latest
    - os: osx
      # .NET Core 2 requires OSX 10.12+
      osx_image: xcode8.3
      jdk:
        - oraclejdk8
      mono:
        - latest

script:
- ./gradlew check -S --info --console plain

after_success:
- bash <(curl -s https://codecov.io/bash) -F unittest

branches:
  only:
  - master
  - /^feature\/.*$/
