language: java
install: true

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8

jdk:
- oraclejdk8

script:
- ./gradlew check --info

after_success:
- bash <(curl -s https://codecov.io/bash) -F unittest

branches:
  only:
  - master
  - /^feature\/.*$/
