// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package software.aws.toolkits.jetbrains.ui

import com.intellij.execution.configurations.GeneralCommandLine
import com.intellij.execution.runners.ExecutionEnvironment
import com.intellij.execution.ui.RunContentDescriptor
import software.aws.toolkits.jetbrains.settings.SamSettings

internal class SamInitRunner {
    /*
$ sam help
Usage: sam init [OPTIONS]
...
...
Options:
  -l, --location TEXT             Template location (git, mercurial, http(s),
                                  zip, path)
  -r, --runtime [python3.6|python2.7|python|nodejs6.10|nodejs8.10|nodejs4.3|nodejs|dotnetcore2.0|dotnetcore1.0|dotnetcore|dotnet|go1.x|go|java8|java]
                                  Lambda Runtime of your app
  -o, --output-dir PATH           Where to output the initialized app into
  -n, --name TEXT                 Name of your project to be generated as a
                                  folder
  --no-input                      Disable prompting and accept default values
                                  defined template config
  --debug                         Turn on debug logging to print debug message
                                  generated by SAM CLI.
  -h, --help                      Show this message and exit.
     */
    init {
        val samCliExecutable = SamSettings.getInstance().executablePath
        val commandLine = GeneralCommandLine(samCliExecutable)
                .withParentEnvironmentType(GeneralCommandLine.ParentEnvironmentType.CONSOLE)
                .withParameters("init")
    }
}