version: 0.2

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'

env:
  variables:
    CI: true

phases:
  install:
    runtime-versions:
      java: openjdk8
      dotnet: 2.2

    commands:
      - echo "Install Mono"
      - apt install -y gnupg ca-certificates
      - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      - echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
      - apt update
      - apt install -y mono-complete

  build:
    commands:
      - chmod +x gradlew
      - ./gradlew check coverageReport --info --full-stacktrace --console plain
      - VCS_COMMIT_ID="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - CI_BUILD_URL=$(echo $CODEBUILD_BUILD_URL | sed 's/#/%23/g') # Encode `#` in the URL because otherwise the url is clipped in the Codecov.io site
      - CI_BUILD_ID="${CODEBUILD_BUILD_ID}"
      - curl -s https://codecov.io/bash > codecov.sh
      - if [ "$CODE_COV_TOKEN" ]; then bash ./codecov.sh -t $CODE_COV_TOKEN -F unittest || true; fi
