version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name integ-test > creds.json
      - apt-get update
      - apt-get install jq
      - apt-get install python3.6
      - export KEY_ID=`jq -r '.Credentials.AccessKeyId' creds.json`
      - export SECRET=`jq -r '.Credentials.SecretAccessKey' creds.json`
      - export TOKEN=`jq -r '.Credentials.SessionToken' creds.json`
      - pip install --user aws-sam-cli
      - pip install --upgrade awscli

  build:
    commands:
      - chmod +x gradlew
      - env AWS_ACCESS_KEY_ID=$KEY_ID AWS_SECRET_ACCESS_KEY=$SECRET AWS_SESSION_TOKEN=$TOKEN SAM_CLI_EXEC=$(python -m site --user-base)/bin/sam ./gradlew integrationTest --info --full-stacktrace