version: 0.2

env:
  variables:
    CI: true

phases:
  install:
    commands:
      - choco install -y --no-progress codecov
      - choco install -y --no-progress dotnetcore-sdk --version 2.2.104
      - choco install -y --no-progress netfx-4.6.1-devpack

  build:
    commands:
      - ./gradlew check coverageReport --info --full-stacktrace --console plain

  post_build:
    commands:
      - |
        if(-Not($Env:CODEBUILD_BUILD_SUCCEEDING -eq "0" -Or $Env:CODE_COV_TOKEN -eq $null)) {
          $env:VCS_COMMIT_ID=$Env:CODEBUILD_RESOLVED_SOURCE_VERSION;
          $env:CI_BUILD_URL=[uri]::EscapeUriString($Env:CODEBUILD_BUILD_URL);
          $env:CI_BUILD_ID=$Env:CODEBUILD_BUILD_ID;
          codecov -t $Env:CODE_COV_TOKEN `
            --flag unittest `
            -f "build/reports/jacoco/coverageReport/coverageReport.xml" `
            -c $Env:CODEBUILD_RESOLVED_SOURCE_VERSION
        }