version: 0.2

cache:
  paths:
    - 'build-cache/caches/'
    - 'build-cache/wrapper/'

env:
  variables:
    CI: true
    LOCAL_ENV_RUN: true
    GRADLE_CACHE_LOCATION: build-cache

phases:
  install:
    commands:
      - |
        if(-Not($Env:CODE_COV_TOKEN -eq $null)) {
            choco install -y --no-progress codecov
        }
      - choco install -y --no-progress dotnetcore-sdk --version 2.2.104
      - choco install -y --no-progress netfx-4.6.1-devpack

  build:
    commands:
      - ./gradlew check coverageReport --info --full-stacktrace --console plain --gradle-user-home $Env:GRADLE_CACHE_LOCATION

  post_build:
    commands:
      - |
        $script:TEST_ARTIFACTS=Join-Path $env:TEMP testArtifacts
        $script:TEST_REPORTS=Join-Path $script:TEST_ARTIFACTS test-reports

        function copyFolder($basedir, $subdir, $destdir) {
          $src = Join-Path "." -ChildPath $basedir | Join-Path -ChildPath $subdir
          $dest = Join-Path $destdir -ChildPath $basedir | Join-Path -ChildPath $subDir
          if( (Get-ChildItem $src -ErrorAction SilentlyContinue | Measure-Object).Count -ne 0) {
            Copy-Item $src $dest -Recurse -Force -ErrorAction SilentlyContinue
          }
        }

        function copyArtifacts($root) {
            copyFolder $root "build/reports/" $script:TEST_ARTIFACTS
            copyFolder $root "build/idea-sandbox/system-test/log/" $script:TEST_ARTIFACTS
            copyFolder $root "build/test-results/test/" $script:TEST_REPORTS
        }

        copyArtifacts "."
        Get-ChildItem -Directory | ForEach-Object { copyArtifacts $_.Name }

        if(-Not($Env:CODEBUILD_BUILD_SUCCEEDING -eq "0" -Or $Env:CODE_COV_TOKEN -eq $null)) {
          $env:VCS_COMMIT_ID=$Env:CODEBUILD_RESOLVED_SOURCE_VERSION;
          $env:CI_BUILD_URL=[uri]::EscapeUriString($Env:CODEBUILD_BUILD_URL);
          $env:CI_BUILD_ID=$Env:CODEBUILD_BUILD_ID;
          codecov -t $Env:CODE_COV_TOKEN `
            --flag unittest `
            -f "build/reports/jacoco/coverageReport/coverageReport.xml" `
            -c $Env:CODEBUILD_RESOLVED_SOURCE_VERSION
        }

reports:
  unit-test:
    files:
      - "**/*"
    base-directory: "$env:TEMP/testArtifacts/test-reports"
    discard-paths: yes

artifacts:
    base-directory: "$env:TEMP/testArtifacts"
    files:
        - "**/*"
