# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, feature/* ]

jobs:
  build:
    name: Mac
    strategy:
      fail-fast: false
      matrix:
        ide: [ 2019.3, 2020.1 ]
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        ALTERNATIVE_IDE_PROFILE_NAME: ${{ matrix.ide }}
      run: ./gradlew --no-daemon check coverageReport --info --debug --full-stacktrace --console plain
