name: Qodana

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feature/* ]


jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.0
