name: CI

on: [pull_request_review]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ./gradlew check -S --info --console plain
