name: Qodana

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feature/* ]

concurrency:
  group: ${{ github.workflow }}${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # PR check
      checks: write
      # PR comments
      pull-requests: write
      # SARIF upload
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Maximize Build Space
        if: runner.os == 'Linux'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          cache-default-branch-only: true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
